// Generated by CoffeeScript 1.12.2
(function() {
  var h, svg, tooltip, w, xpadding;

  w = 960;

  h = 500;

  svg = d3.select('body').append('svg').attr('width', w).attr('height', h);

  xpadding = 50.0;

  tooltip = d3.select("body").append("div").style("position", "absolute").style("z-index", "10").style("visibility", "hidden").text("a simple tooltip");

  d3.json('data.json', function(data) {
    var query_len, xScale, yScale;
    query_len = data.alignments[0].query_length;
    xScale = d3.scaleLinear().domain([0, query_len]).range([0 + xpadding, w - xpadding]);
    yScale = d3.scaleLinear().domain([0, data.alignments.length]).range([120, 500]);
    svg.append('rect').attr('x', xScale(0)).attr('width', xScale(query_len)).attr('y', 100).attr('height', 10).attr('opacity', 0.5).attr('fill', 'blue');
    return svg.selectAll('rects').data(data.alignments).enter().append('rect').attr('x', function(d) {
      return xScale(d.q_start);
    }).attr('y', function(d, i) {
      return 120 + i * 10;
    }).attr('width', function(d) {
      return xScale(d.q_end) - xScale(d.q_start);
    }).attr('height', 7).attr('fill', 'black').attr('opacity', 0.9).on("mouseover", function(d) {
      tooltip.text(d.subject_acc + ' ' + d.q_start + ' (' + xScale(d.q_start) + ') ' + d.q_end + ' (' + xScale(d.q_end) + ') ');
      return tooltip.style("visibility", "visible");
    }).on("mouseout", function() {
      return tooltip.style("visibility", "hidden");
    });
  });

}).call(this);

//# sourceMappingURL=baseviewer.js.map
