// Generated by CoffeeScript 1.12.2
(function() {
  var f, h, svg, w, xScale;

  w = 500;

  h = 400;

  svg = d3.select('body').append('svg').attr('width', w).attr('height', h);

  xScale = d3.scaleLinear().domain([-50, 150]).range([50, 400]);

  f = function(x, x2, t, y) {
    svg.append('rect').attr('x', xScale(x)).attr('width', xScale(x2) - xScale(x)).attr('y', 100).attr('height', 10).attr('opacity', 0.5).attr('fill', 'blue');
    return svg.append('text').attr('x', function(d) {
      return xScale((x + x2) / 2);
    }).attr('y', 100 - y).text(t).attr("text-anchor", "middle");
  };

  f(-50, -20, 'Homology', 10);

  f(-19, -10, 'long primer', 20);

  f(-9, 29, 'extra primer', 30);

  f(30, 70, 'two extra primers', 10);

  f(71, 125, 'No man', 20);

  f(126, 149, 'Synthesis', 30);

}).call(this);

//# sourceMappingURL=cost_analysis.js.map
