// Generated by CoffeeScript 1.12.2
(function() {
  var h, svg, w;

  w = 960;

  h = 5000;

  svg = d3.select('body').append('svg').attr('width', w).attr('height', h);

}).call(this);

//# sourceMappingURL=plasmid_editor.js.map
